include: package:very_good_analysis/analysis_options.11.0.0.yaml

plugins:
  riverpod_lint: 3.1.9

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    public_member_api_docs: false
